ords = [0, 0, 0, 0, 0,
        0, 0, 0, 0, 0,
        0, 1, 1, 0, 0]
exps = [
(['name', 'age'], [('Brigitte Bardot', 89)]),
(['name'], [('Olivia de Havilland',)]),
(['episode'], [('Souvenir from Singapore',)]),
(['character', 'name'],
 [('Becket', 'Richard Burton'),
  ('Christine', 'Marlene Dietrich'),
  ('Margo', 'Bette Davis'),
  ('Paul', 'Marlon Brando'),
  ('Spartacus', 'Kirk Douglas')]),
(['title', 'syear'],
 [('1941', 1979),
  ('1984', 1984),
  ('Amarcord', 1973),
  ('Apocalypse Now', 1979),
  ('Becket', 1964),
  ('Contempt', 1963),
  ('Cries & Whispers', 1972),
  ('Fanny and Alexander', 1982),
  ('Judgment at Nuremberg', 1961),
  ('La Dolce Vita', 1960),
  ('Last Tango in Paris', 1972),
  ('Love on a Pillow', 1962),
  ('On Golden Pond', 1981),
  ('Platoon', 1986),
  ('Spartacus', 1960),
  ('The Blues Brothers', 1980),
  ('The Day of the Dolphin', 1973),
  ('The Final Countdown', 1980),
  ('The Godfather', 1972),
  ('The Mirror Has Two Faces', 1996),
  ('The Shootist', 1976),
  ('The Spy Who Came in from the Cold', 1965),
  ('The Towering Inferno', 1974),
  ('The Truth', 1960),
  ('Twins', 1988),
  ('What Ever Happened to Baby Jane?', 1962)]),
(['title', 'runtime', 'syear'],
 [('12 Angry Men', 96, 1957),
  ('All About Eve', 138, 1950),
  ('Amarcord', 123, 1973),
  ('Angels with Dirty Faces', 97, 1938),
  ('Apocalypse Now', 147, 1979),
  ('Becket', 148, 1964),
  ('Casablanca', 102, 1942),
  ('Contempt', 103, 1963),
  ('Cries & Whispers', 91, 1972),
  ('East of Eden', 118, 1955),
  ('Fanny and Alexander', 188, 1982),
  ('Gaslight', 114, 1944),
  ('Giant', 201, 1956),
  ('Gone with the Wind', 238, 1939),
  ('High Noon', 85, 1952),
  ('In a Lonely Place', 94, 1950),
  ('Judgment at Nuremberg', 179, 1961),
  ('La Dolce Vita', 174, 1960),
  ('Mr. Deeds Goes to Town', 115, 1936),
  ('Nights of Cabiria', 110, 1957),
  ('Notorious', 102, 1946),
  ('Now, Voyager', 117, 1942),
  ('On Golden Pond', 109, 1981),
  ('On the Waterfront', 108, 1954),
  ('Paths of Glory', 88, 1957),
  ('Platoon', 120, 1986),
  ('Rebel Without a Cause', 111, 1955),
  ('Sergeant York', 134, 1941),
  ('Spartacus', 197, 1960),
  ('Spellbound', 111, 1945),
  ('The Adventures of Robin Hood', 102, 1938),
  ('The African Queen', 105, 1951),
  ('The Big Sleep', 114, 1946),
  ('The Blues Brothers', 133, 1980),
  ('The Godfather', 175, 1972),
  ('The Grapes of Wrath', 129, 1940),
  ('The Heiress', 115, 1949),
  ('The Roaring Twenties', 106, 1939),
  ('The Seventh Seal', 96, 1957),
  ('The Shootist', 100, 1976),
  ('The Spy Who Came in from the Cold', 112, 1965),
  ('To Have and Have Not', 100, 1944),
  ('Touch of Evil', 95, 1958),
  ('What Ever Happened to Baby Jane?', 134, 1962),
  ('White Heat', 114, 1949),
  ('Wild Strawberries', 91, 1957),
  ('Witness for the Prosecution', 116, 1957),
  ('Yankee Doodle Dandy', 126, 1942)]),
(['director', 'title'],
 [('Federico Fellini', 'Amarcord'),
  ('Federico Fellini', 'La Dolce Vita'),
  ('Federico Fellini', 'Nights of Cabiria'),
  ('Ingmar Bergman', 'Cries & Whispers'),
  ('Ingmar Bergman', 'Fanny and Alexander'),
  ('Ingmar Bergman', 'The Seventh Seal'),
  ('Ingmar Bergman', 'Wild Strawberries')]),
(['name', 'birth', 'death'],
 [('Federico Fellini', 1920, 1993),
  ('Georges Delerue', 1925, 1992),
  ('Ingmar Bergman', 1918, 2007)]),
(['name', 'count', 'earliest', 'longest'],
 [('Henry Fonda', 3, 1940, 129),
  ('Marlene Dietrich', 3, 1930, 179),
  ('Humphrey Bogart', 6, 1938, 114),
  ('Doris Day', 4, 1953, 122),
  ('John Belushi', 2, 1979, 133),
  ('James Cagney', 5, 1938, 126),
  ('Marlon Brando', 4, 1954, 175),
  ('Brigitte Bardot', 3, 1956, 128),
  ('Kirk Douglas', 4, 1956, 197),
  ('Ingrid Bergman', 4, 1942, 114),
  ('Richard Burton', 2, 1964, 148),
  ('Lauren Bacall', 3, 1946, 126),
  ('Fred Astaire', 3, 1939, 134),
  ('Olivia de Havilland', 3, 1938, 115),
  ('Gary Cooper', 4, 1936, 170),
  ('James Dean', 3, 1955, 201),
  ('Bette Davis', 4, 1939, 138)]),
(['name', 'count'],
 [('James Dean', 3),
  ('Kirk Douglas', 4),
  ('Brigitte Bardot', 3),
  ('Doris Day', 4),
  ('Marlon Brando', 4)]),
(['name', 'character'],
 [('Richard Burton', 'Becket'), ('Richard Burton', 'Thomas Becket')]),
(['title', 'season', 'episode', 'name'],
 [('Schlitz Playhouse', 8, 1, 'A Thing to Fight For'),
  ('Schlitz Playhouse', 8, 2, 'The Hasty Hanging'),
  ('Schlitz Playhouse', 8, 3, 'The Trouble with Ruth'),
  ('Schlitz Playhouse', 8, 4, 'False Impression'),
  ('Schlitz Playhouse', 8, 5, 'Last Edition'),
  ('Schlitz Playhouse', 8, 6, 'Third Son'),
  ('Schlitz Playhouse', 8, 7, 'No Answer'),
  ('Schlitz Playhouse', 8, 8, 'A Fistful of Love'),
  ('Schlitz Playhouse', 8, 9, None),
  ('Schlitz Playhouse', 8, 10, 'And Practically Strangers'),
  ('Schlitz Playhouse', 8, 11, 'The Man Who Had No Friends'),
  ('Schlitz Playhouse', 8, 12, 'On the Brink'),
  ('Schlitz Playhouse', 8, 13, 'Ivy League'),
  ('Schlitz Playhouse', 8, 14, 'The Salted Mine'),
  ('Schlitz Playhouse', 8, 15, 'The Rumor'),
  ('Schlitz Playhouse', 8, 16, 'Hostage'),
  ('Schlitz Playhouse', 8, 17, 'Cowboy Five Seven'),
  ('Schlitz Playhouse', 8, 18, 'Ballad to Die For'),
  ('Schlitz Playhouse', 7, 1, 'Three Dollar Bill'),
  ('Schlitz Playhouse', 7, 2, 'One Way Out'),
  ('Schlitz Playhouse', 7, 3, None),
  ('Schlitz Playhouse', 7, 4, None),
  ('Schlitz Playhouse', 7, 5, 'Smarty'),
  ('Schlitz Playhouse', 7, 6, 'High Barrier'),
  ('Schlitz Playhouse', 7, 7, 'Bitter Parting'),
  ('Schlitz Playhouse', 7, 8, 'Dual Control'),
  ('Schlitz Playhouse', 7, 9, 'The Hole Card'),
  ('Schlitz Playhouse', 7, 10, 'The Lonely Wizard'),
  ('Schlitz Playhouse', 7, 11, 'No Second Helping'),
  ('Schlitz Playhouse', 7, 12, None),
  ('Schlitz Playhouse', 7, 13, 'Neighbors'),
  ('Schlitz Playhouse', 7, 14, 'French Provincial'),
  ('Schlitz Playhouse', 7, 15, 'Rich Man, Poor Man'),
  ('Schlitz Playhouse', 7, 16, 'Pattern for Death'),
  ('Schlitz Playhouse', 7, 17, None),
  ('Schlitz Playhouse', 7, 18, 'Home Again'),
  ('Schlitz Playhouse', 7, 19, 'No Boat for Four Months'),
  ('Schlitz Playhouse', 7, 20, 'Heroes Never Grow Up'),
  ('Schlitz Playhouse', 7, 21, 'East of the Moon'),
  ('Schlitz Playhouse', 7, 22, 'Man on a Rack'),
  ('Schlitz Playhouse', 7, 23, 'Two Lives Have I'),
  ('Schlitz Playhouse', 7, 24, 'Night of the Stranger'),
  ('Schlitz Playhouse', 7, 25, 'The Honor System'),
  ('Schlitz Playhouse', 7, 26, None),
  ('Schlitz Playhouse', 7, 27, 'I Shot a Prowler'),
  ('Schlitz Playhouse', 7, 28, 'Papa Said No'),
  ('Schlitz Playhouse', 7, 29, 'Secrets of the Old Bailey'),
  ('Schlitz Playhouse', 7, 30, 'A Contest of Ladies'),
  ('Schlitz Playhouse', 7, 31, 'The Kind Mr. Smith'),
  ('Schlitz Playhouse', 7, 32, 'Penny Wise'),
  ('Schlitz Playhouse', 7, 33, 'The Town That Slept with the Lights On'),
  ('Schlitz Playhouse', 7, 34, 'Lottery for Revenge'),
  ('Schlitz Playhouse', 7, 35, 'Way of the West'),
  ('Schlitz Playhouse', 7, 36, 'Long Distance'),
  ('Schlitz Playhouse', 7, 37, None),
  ('Schlitz Playhouse', 7, 38, 'Curfew at Midnight'),
  ('Schlitz Playhouse', 7, 39, 'False Alarm'),
  ('Schlitz Playhouse', 6, 1, 'Moment of Vengeance'),
  ('Schlitz Playhouse', 6, 2, 'The House That Jackson Built'),
  ('Schlitz Playhouse', 6, 3, 'The Trophy'),
  ('Schlitz Playhouse', 6, 4, None),
  ('Schlitz Playhouse', 6, 5, 'Always the Best Man'),
  ('Schlitz Playhouse', 6, 6, None),
  ('Schlitz Playhouse', 6, 7, 'The Night They Won the Oscar'),
  ('Schlitz Playhouse', 6, 8, 'Explosion'),
  ('Schlitz Playhouse', 6, 9, 'The Letter'),
  ('Schlitz Playhouse', 6, 10, 'Once Upon a Crime'),
  ('Schlitz Playhouse', 6, 11, 'Washington Incident'),
  ('Schlitz Playhouse', 6, 12, 'A Tale of Wells Fargo'),
  ('Schlitz Playhouse', 6, 13, 'A Light in the Desert'),
  ('Schlitz Playhouse', 6, 14, 'The Big Payoff'),
  ('Schlitz Playhouse', 6, 15, 'The Lady Was a Flop'),
  ('Schlitz Playhouse', 6, 16, 'Tower Room 14-A'),
  ('Schlitz Playhouse', 6, 17, 'Terror in the Streets'),
  ('Schlitz Playhouse', 6, 18, 'The Enchanted'),
  ('Schlitz Playhouse', 6, 19, 'One Left Over'),
  ('Schlitz Playhouse', 6, 20, 'Sometimes You Break Even'),
  ('Schlitz Playhouse', 6, 21, 'Night Drive'),
  ('Schlitz Playhouse', 6, 22, 'The Wedding Present'),
  ('Schlitz Playhouse', 6, 23, 'The Life You Save'),
  ('Schlitz Playhouse', 6, 24, 'Carriage from Britain'),
  ('Schlitz Playhouse', 6, 25, 'The Girl in the Grass'),
  ('Schlitz Playhouse', 6, 26, 'For Better, for Worse'),
  ('Schlitz Playhouse', 6, 27, 'The Restless Gun'),
  ('Schlitz Playhouse', 6, 28, 'Clothes Make the Man'),
  ('Schlitz Playhouse', 6, 29, 'The Blue Hotel'),
  ('Schlitz Playhouse', 6, 30, 'Girl with a Glow'),
  ('Schlitz Playhouse', 6, 31, 'Hey, Mac'),
  ('Schlitz Playhouse', 6, 32, 'The Traveling Corpse'),
  ('Schlitz Playhouse', 6, 33, 'The Dead Are Silent'),
  ('Schlitz Playhouse', 6, 34, 'Switch Station'),
  ('Schlitz Playhouse', 6, 35, 'Sister Louise Goes to Town'),
  ('Schlitz Playhouse', 6, 36, 'The Sword'),
  ('Schlitz Playhouse', 6, 37, 'An Old Spanish Custom'),
  ('Schlitz Playhouse', 6, 38, 'Storm Over Rapallo'),
  ('Schlitz Playhouse', 6, 39, 'Fifty Beautiful Girls'),
  ('Schlitz Playhouse', 6, 40, 'Sporting Chance'),
  ('Schlitz Playhouse', 6, 41, 'Easy Going Man'),
  ('Schlitz Playhouse', 6, 42, 'Hands of the Enemy'),
  ('Schlitz Playhouse', 6, 43, 'The Face of a Killer'),
  ('Schlitz Playhouse', 6, 44, None),
  ('Schlitz Playhouse', 6, 45, 'Always Open and Shut'),
  ('Schlitz Playhouse', 5, 1, 'The Last Out'),
  ('Schlitz Playhouse', 5, 2, None),
  ('Schlitz Playhouse', 5, 3, 'Two-Bit Gangster'),
  ('Schlitz Playhouse', 5, 4, 'The Girl Who Scared Men Off'),
  ('Schlitz Playhouse', 5, 5, 'Nothing to Do Till Next Fall'),
  ('Schlitz Playhouse', 5, 6, 'A Gift of Life'),
  ('Schlitz Playhouse', 5, 7, 'No Trial by Jury'),
  ('Schlitz Playhouse', 5, 8, 'Night of the Big Swamp'),
  ('Schlitz Playhouse', 5, 9, 'The Careless Cadet'),
  ('Schlitz Playhouse', 5, 10, 'Moment of Triumph'),
  ('Schlitz Playhouse', 5, 11, 'On the Nose'),
  ('Schlitz Playhouse', 5, 12, 'The Baited Hook'),
  ('Schlitz Playhouse', 5, 13, 'Christmas Guest'),
  ('Schlitz Playhouse', 5, 14, 'Well of Anger'),
  ('Schlitz Playhouse', 5, 15, 'Fool Proof'),
  ('Schlitz Playhouse', 5, 16, None),
  ('Schlitz Playhouse', 5, 17, 'The Big Payday'),
  ('Schlitz Playhouse', 5, 18, 'The Day I Died'),
  ('Schlitz Playhouse', 5, 19, 'The Gentle Stranger'),
  ('Schlitz Playhouse', 5, 20, 'Top Man'),
  ('Schlitz Playhouse', 5, 21, 'On a Dark Night'),
  ('Schlitz Playhouse', 5, 22, 'Ordeal'),
  ('Schlitz Playhouse', 5, 23, 'Showdown at Painted Rock'),
  ('Schlitz Playhouse', 5, 24, 'Web of Circumstance'),
  ('Schlitz Playhouse', 5, 25, 'The Young and the Brave'),
  ('Schlitz Playhouse', 5, 26, 'The Waiting House'),
  ('Schlitz Playhouse', 5, 27, 'The Finger of God'),
  ('Schlitz Playhouse', 5, 28, 'Angels in the Sky'),
  ('Schlitz Playhouse', 5, 29, 'The Bitter Land'),
  ('Schlitz Playhouse', 5, 30, 'The Mysterious Cargo'),
  ('Schlitz Playhouse', 5, 31, 'Step Right Up and Die'),
  ('Schlitz Playhouse', 5, 32, 'Formosa Patrol'),
  ('Schlitz Playhouse', 5, 33, 'Plague Ship'),
  ('Schlitz Playhouse', 5, 34, 'Officer Needs Help'),
  ('Schlitz Playhouse', 5, 35, 'Date for Tomorrow'),
  ('Schlitz Playhouse', 5, 36, 'The Roustabout'),
  ('Schlitz Playhouse', 5, 37, 'Pattern for Pursuit'),
  ('Schlitz Playhouse', 5, 38, 'Witness to Condemn'),
  ('Schlitz Playhouse', 5, 39, 'Weapon of Courage'),
  ('Schlitz Playhouse', 5, 40, 'The Mechanical Cook'),
  ('Schlitz Playhouse', 5, 41, 'The Happy Sun'),
  ('Schlitz Playhouse', 5, 42, 'The Bankmouse'),
  ('Schlitz Playhouse', 5, 43, 'Dara'),
  ('Schlitz Playhouse', 5, 44, 'Flowers for Jenny'),
  ('Schlitz Playhouse', 5, 46, 'Repercussion'),
  ('Schlitz Playhouse', 5, 48, 'Strange Defense'),
  ('Schlitz Playhouse', 5, 49, None),
  ('Schlitz Playhouse', 5, 50, 'The Press Agent'),
  ('Schlitz Playhouse', 5, 51, 'Midnight Kill'),
  ('Schlitz Playhouse', 5, 52, 'Top Secret'),
  ('Schlitz Playhouse', 4, 1, 'The Secret'),
  ('Schlitz Playhouse', 4, 2, None),
  ('Schlitz Playhouse', 4, 3, 'The Pipe'),
  ('Schlitz Playhouse', 4, 4, 'The Viking'),
  ('Schlitz Playhouse', 4, 5, 'The Net Draws Tight'),
  ('Schlitz Playhouse', 4, 6, None),
  ('Schlitz Playhouse', 4, 7, 'The Best of Everything'),
  ('Schlitz Playhouse', 4, 8, 'The Sensation Club'),
  ('Schlitz Playhouse', 4, 9, 'No Rescue'),
  ('Schlitz Playhouse', 4, 10, 'Midnight Haul'),
  ('Schlitz Playhouse', 4, 11, 'The Long Trail'),
  ('Schlitz Playhouse', 4, 12, 'Mystery of Murder'),
  ('Schlitz Playhouse', 4, 13, 'Volturio Investigates'),
  ('Schlitz Playhouse', 4, 14, 'Spangal Island'),
  ('Schlitz Playhouse', 4, 15, 'Woman Expert'),
  ('Schlitz Playhouse', 4, 16, 'Day of Good News'),
  ('Schlitz Playhouse', 4, 17, 'The Dumbest Man in the Army'),
  ('Schlitz Playhouse', 4, 18, 'The Cool One'),
  ('Schlitz Playhouse', 4, 19, 'Man Out of the Rain'),
  ('Schlitz Playhouse', 4, 20, 'Underground'),
  ('Schlitz Playhouse', 4, 21, 'Murder in Paradise'),
  ('Schlitz Playhouse', 4, 22, 'The Last Pilot Schooner'),
  ('Schlitz Playhouse', 4, 23, 'The Schoolmarm'),
  ('Schlitz Playhouse', 4, 24, 'The Way to Freedom'),
  ('Schlitz Playhouse', 4, 25, 'Fast Break'),
  ('Schlitz Playhouse', 4, 26, 'Fedar'),
  ('Schlitz Playhouse', 4, 27, 'Visitor in the Night'),
  ('Schlitz Playhouse', 4, 28, 'Ride to the West'),
  ('Schlitz Playhouse', 4, 29, 'Log the Man Innocent'),
  ('Schlitz Playhouse', 4, 30, 'Tourists--Overnight'),
  ('Schlitz Playhouse', 4, 31, 'Mr. Ears'),
  ('Schlitz Playhouse', 4, 32, None),
  ('Schlitz Playhouse', 4, 33, None),
  ('Schlitz Playhouse', 4, 34, 'The Brute Next Door'),
  ('Schlitz Playhouse', 4, 35, 'The Unlighted Road'),
  ('Schlitz Playhouse', 4, 36, 'Too Many Nelsons'),
  ('Schlitz Playhouse', 4, 37, 'Sentence of Death'),
  ('Schlitz Playhouse', 4, 38, 'The Argonauts'),
  ('Schlitz Playhouse', 4, 39, 'Visa for X'),
  ('Schlitz Playhouse', 4, 40, None),
  ('Schlitz Playhouse', 4, 41, 'A Mule for Santa Fe'),
  ('Schlitz Playhouse', 4, 42, 'Splendid with Swords'),
  ('Schlitz Playhouse', 4, 43, 'The Ordeal of Dr. Sutton'),
  ('Schlitz Playhouse', 4, 44, 'Ambitious Cop'),
  ('Schlitz Playhouse', 4, 45, 'Meet Mr. Justice'),
  ('Schlitz Playhouse', 4, 46, 'Visibility Zero'),
  ('Schlitz Playhouse', 4, 47, 'The Direct Approach'),
  ('Schlitz Playhouse', 4, 48, 'Too Late to Run'),
  ('Schlitz Playhouse', 4, 49, 'On Leave'),
  ('Schlitz Playhouse', 4, 50, 'Jury of One'),
  ('Schlitz Playhouse', 4, 51, 'The Case for the State'),
  ('Schlitz Playhouse', 4, 52, 'Three Months to Remember'),
  ('Schlitz Playhouse', 4, 53, 'The Uninhibited Female'),
  ('Schlitz Playhouse', 4, 54, 'Wild Call'),
  ('Schlitz Playhouse', 4, 55, 'The Quitter'),
  ('Schlitz Playhouse', 3, 1, 'The Perfect Secretary'),
  ('Schlitz Playhouse', 3, 2, 'Lost and Found'),
  ('Schlitz Playhouse', 3, 3, 'Boomerang'),
  ('Schlitz Playhouse', 3, 4, 'Desert Tragedy'),
  ('Schlitz Playhouse', 3, 5, 'The Prize'),
  ('Schlitz Playhouse', 3, 6, 'The Long Shot'),
  ('Schlitz Playhouse', 3, 7, 'In the Pincers'),
  ('Schlitz Playhouse', 3, 8, 'Second Sight'),
  ('Schlitz Playhouse', 3, 9, 'The Soil'),
  ('Schlitz Playhouse', 3, 10, None),
  ('Schlitz Playhouse', 3, 11, 'Lucky Thirteen'),
  ('Schlitz Playhouse', 3, 12, 'Fresh Start'),
  ('Schlitz Playhouse', 3, 13, 'The Closed Door'),
  ('Schlitz Playhouse', 3, 14, 'Storm Swept'),
  ('Schlitz Playhouse', 3, 15, 'No Compromise'),
  ('Schlitz Playhouse', 3, 16, 'Part of the Game'),
  ('Schlitz Playhouse', 3, 17, 'The Baker of Barnbury'),
  ('Schlitz Playhouse', 3, 18, 'Go Away a Winner'),
  ('Schlitz Playhouse', 3, 19, 'Rim of Violence'),
  ('Schlitz Playhouse', 3, 20, 'Pearl-Handled Guns'),
  ('Schlitz Playhouse', 3, 21, 'At the Natchez Inn'),
  ('Schlitz Playhouse', 3, 22, 'Give the Guy a Break'),
  ('Schlitz Playhouse', 3, 23, None),
  ('Schlitz Playhouse', 3, 24, 'Man from Outside'),
  ('Schlitz Playhouse', 3, 25, 'The Jungle Trap'),
  ('Schlitz Playhouse', 3, 26, 'Night Ride to Butte'),
  ('Schlitz Playhouse', 3, 27, 'The Great Lady'),
  ('Schlitz Playhouse', 3, 28, 'Groundloop'),
  ('Schlitz Playhouse', 3, 29, 'Her Kind of Honor'),
  ('Schlitz Playhouse', 3, 30, 'The Edge of Battle'),
  ('Schlitz Playhouse', 3, 31, 'Tapu'),
  ('Schlitz Playhouse', 3, 32, 'The Plugged Nickel'),
  ('Schlitz Playhouse', 3, 33, 'Something Wonderful'),
  ('Schlitz Playhouse', 3, 34, 'Dawn at Damascus'),
  ('Schlitz Playhouse', 3, 35, 'Decision at Sea'),
  ('Schlitz Playhouse', 3, 36, 'Prisoner in the Town'),
  ('Schlitz Playhouse', 3, 37, 'The Pearl Street Incident'),
  ('Schlitz Playhouse', 3, 38, 'Blizzard Bound'),
  ('Schlitz Playhouse', 3, 39, 'Little War at San Dede'),
  ('Schlitz Playhouse', 3, 40, 'The Whale on the Beach'),
  ('Schlitz Playhouse', 3, 41, 'The Treasure of Santo Domingo'),
  ('Schlitz Playhouse', 3, 42, 'The Black Mate'),
  ('Schlitz Playhouse', 3, 43, None),
  ('Schlitz Playhouse', 3, 44, 'How the Brigadier Won His Medals'),
  ('Schlitz Playhouse', 3, 45, 'Rabbit Foot'),
  ('Schlitz Playhouse', 3, 46, 'Showdown at Sunset'),
  ('Schlitz Playhouse', 3, 47, None),
  ('Schlitz Playhouse', 3, 48, 'By-Line'),
  ('Schlitz Playhouse', 3, 49, 'The Roman and the Renegade'),
  ('Schlitz Playhouse', 3, 50, 'Gift of the Devil'),
  ('Schlitz Playhouse', 3, 51, 'Captain in Command'),
  ('Schlitz Playhouse', 3, 52, 'Hemmed In'),
  ('Schlitz Playhouse', 3, 53, 'Delay at Fort Bess'),
  ('Schlitz Playhouse', 2, 1, 'Homecoming'),
  ('Schlitz Playhouse', 2, 2, 'The Marriage of Lit-Lit'),
  ('Schlitz Playhouse', 2, 3, 'I Want to Be a Movie Star'),
  ('Schlitz Playhouse', 2, 4, 'The Trail'),
  ('Schlitz Playhouse', 2, 5, 'Come What May'),
  ('Schlitz Playhouse', 2, 6, 'Trouble in Pier Twelve'),
  ('Schlitz Playhouse', 2, 7, 'This Plane for Hire'),
  ('Schlitz Playhouse', 2, 8, 'Drawing Room A'),
  ('Schlitz Playhouse', 2, 9, 'Enchanted Evening'),
  ('Schlitz Playhouse', 2, 10, 'Tango'),
  ('Schlitz Playhouse', 2, 11, 'The House of Pride'),
  ('Schlitz Playhouse', 2, 12, None),
  ('Schlitz Playhouse', 2, 13, 'Barrow Street'),
  ('Schlitz Playhouse', 2, 14, 'Mr. Thayer'),
  ('Schlitz Playhouse', 2, 15, 'The White Cream Pitcher'),
  ('Schlitz Playhouse', 2, 16, 'The Playwright'),
  ('Schlitz Playhouse', 2, 17, 'A String of Beads'),
  ('Schlitz Playhouse', 2, 18, 'Jenny'),
  ('Schlitz Playhouse', 2, 19, 'The Unopened Letter'),
  ('Schlitz Playhouse', 2, 21, 'Guardian of the Clock'),
  ('Schlitz Playhouse', 2, 22, 'Point of Honor'),
  ('Schlitz Playhouse', 2, 23, 'Manhattan Robin Hood'),
  ('Schlitz Playhouse', 2, 24, 'Mr. Greentree and Friend'),
  ('Schlitz Playhouse', 2, 25, None),
  ('Schlitz Playhouse', 2, 26, 'Girl of My Dreams'),
  ('Schlitz Playhouse', 2, 27, None),
  ('Schlitz Playhouse', 2, 28, 'Nineteen Rue Marie'),
  ('Schlitz Playhouse', 2, 29, None),
  ('Schlitz Playhouse', 2, 30, 'Happy Ending'),
  ('Schlitz Playhouse', 2, 31, 'The Governess'),
  ('Schlitz Playhouse', 2, 32, 'The Mirror'),
  ('Schlitz Playhouse', 2, 33, 'Papa Goes to the Ball'),
  ('Schlitz Playhouse', 2, 34, 'Allen of Harper'),
  ('Schlitz Playhouse', 2, 35, 'Medicine Woman'),
  ('Schlitz Playhouse', 2, 36, 'The Copper Ring'),
  ('Schlitz Playhouse', 2, 37, 'Vacation for Ginny'),
  ('Schlitz Playhouse', 2, 38, 'Pursuit'),
  ('Schlitz Playhouse', 2, 39, 'The Girl That I Married'),
  ('Schlitz Playhouse', 2, 40, 'Twenty-two Sycamore Road'),
  ('Schlitz Playhouse', 2, 41, 'The Widow Makes Three'),
  ('Schlitz Playhouse', 2, 42, 'Operation Riviera'),
  ('Schlitz Playhouse', 2, 43, 'The Ledge'),
  ('Schlitz Playhouse', 2, 44, 'Richard and the Lion'),
  ('Schlitz Playhouse', 2, 45, 'Storm Warnings'),
  ('Schlitz Playhouse', 2, 46, 'The Journey'),
  ('Schlitz Playhouse', 2, 47, 'Knave of Hearts'),
  ('Schlitz Playhouse', 2, 48, 'The Doctor Comes Home'),
  ('Schlitz Playhouse', 2, 49, 'Simplon Express'),
  ('Schlitz Playhouse', 2, 50, 'Miracle in the Night'),
  ('Schlitz Playhouse', 2, 51, 'Sheila'),
  ('Schlitz Playhouse', 2, 52, 'Two Loves Have I'),
  ('Schlitz Playhouse', 1, 1, 'Not a Chance'),
  ('Schlitz Playhouse', 1, 2, 'The Name Is Bellingham'),
  ('Schlitz Playhouse', 1, 3, 'Never Wave at a WAC'),
  ('Schlitz Playhouse', 1, 4, 'Still Life'),
  ('Schlitz Playhouse', 1, 5, 'The Lucky Touch'),
  ('Schlitz Playhouse', 1, 6, 'Decision and Daniel Webster'),
  ('Schlitz Playhouse', 1, 7, 'The Memories of Aimee Durant'),
  ('Schlitz Playhouse', 1, 8, 'One Is a Lonesome Number'),
  ('Schlitz Playhouse', 1, 9, 'Two Living and One Dead'),
  ('Schlitz Playhouse', 1, 10, 'The Nymph and the Lamp'),
  ('Schlitz Playhouse', 1, 11, 'Exit'),
  ('Schlitz Playhouse', 1, 12, 'Dark Fleece'),
  ('Schlitz Playhouse', 1, 13, 'Girl in a Million'),
  ('Schlitz Playhouse', 1, 14, 'Clean Sweep for Lavinia'),
  ('Schlitz Playhouse', 1, 15, 'Billy Budd'),
  ('Schlitz Playhouse', 1, 16, 'The Man That I Marry'),
  ('Schlitz Playhouse', 1, 17, 'P.G.'),
  ('Schlitz Playhouse', 1, 18, 'Lady with a Will'),
  ('Schlitz Playhouse', 1, 19, 'The Daughter'),
  ('Schlitz Playhouse', 1, 20, 'Fifty Grand'),
  ('Schlitz Playhouse', 1, 21, 'World So Wide'),
  ('Schlitz Playhouse', 1, 22, 'Apple of His Eye'),
  ('Schlitz Playhouse', 1, 23, 'The Haunted Heart'),
  ('Schlitz Playhouse', 1, 24, 'Make Way for Teddy'),
  ('Schlitz Playhouse', 1, 25, 'The Human Touch'),
  ('Schlitz Playhouse', 1, 26, 'The Autobiography of Grandma Moses'),
  ('Schlitz Playhouse', 1, 27, 'The Experiment'),
  ('Schlitz Playhouse', 1, 28, None),
  ('Schlitz Playhouse', 1, 29, None),
  ('Schlitz Playhouse', 1, 30, 'Fear'),
  ('Schlitz Playhouse', 1, 31, 'Doctors Should Never Marry'),
  ('Schlitz Playhouse', 1, 32, 'Appointment with the Past'),
  ('Schlitz Playhouse', 1, 33, 'Autumn in New York'),
  ('Schlitz Playhouse', 1, 34, 'Love Came Late'),
  ('Schlitz Playhouse', 1, 35, 'A Quarter for Your Troubles'),
  ('Schlitz Playhouse', 1, 36, 'Souvenir from Singapore'),
  ('Schlitz Playhouse', 1, 37, 'Dress in the Window'),
  ('Schlitz Playhouse', 1, 38, 'Say Hello to Pamela'),
  ('Schlitz Playhouse', 1, 39, 'The Von Linden File'),
  ('Schlitz Playhouse', 1, 40, 'The House of Death'),
  ('Schlitz Playhouse', 1, 41, 'A Southern Lady'),
  ('Schlitz Playhouse', 1, 42, 'Early Space Conquerors'),
  ('Schlitz Playhouse', 1, 43, None),
  ('Schlitz Playhouse', 1, 44, 'Crossroads'),
  ('Schlitz Playhouse', 1, 45, 'So Help Me'),
  ('Schlitz Playhouse', 1, 46, 'Double Exposure'),
  ('Schlitz Playhouse', 1, 47, 'Mr. And Mrs. Trubble or The Tubbles'),
  ('Schlitz Playhouse', 1, 48, 'Port of Call')]),
(['genre', 'count'],
 [('Film-Noir', 9),
  ('Adventure', 7),
  ('Biography', 7),
  ('Mystery', 7),
  ('Thriller', 7),
  ('War', 7),
  ('Action', 6)]),
(['name', 'genre'],
 [('Doris Day', 'Biography'),
  ('Doris Day', 'Comedy'),
  ('Doris Day', 'Drama'),
  ('Doris Day', 'Music'),
  ('Doris Day', 'Musical'),
  ('Doris Day', 'Romance'),
  ('Doris Day', 'Thriller'),
  ('Doris Day', 'Western'),
  ('Gary Cooper', 'Adventure'),
  ('Gary Cooper', 'Biography'),
  ('Gary Cooper', 'Comedy'),
  ('Gary Cooper', 'Drama'),
  ('Gary Cooper', 'History'),
  ('Gary Cooper', 'Romance'),
  ('Gary Cooper', 'Thriller'),
  ('Gary Cooper', 'Western'),
  ('Lauren Bacall', 'Comedy'),
  ('Lauren Bacall', 'Crime'),
  ('Lauren Bacall', 'Drama'),
  ('Lauren Bacall', 'Film-Noir'),
  ('Lauren Bacall', 'Mystery'),
  ('Lauren Bacall', 'Romance'),
  ('Lauren Bacall', 'Western')]),
(['year', 'genre'],
 [(1960, 'Drama'),
  (1961, 'Drama'),
  (1961, 'War'),
  (1962, 'Drama'),
  (1963, 'Drama'),
  (1963, 'Romance'),
  (1964, 'Biography'),
  (1964, 'Drama'),
  (1964, 'History'),
  (1965, 'Drama'),
  (1965, 'Thriller'),
  (1966, None),
  (1967, None),
  (1968, None),
  (1969, None),
  (1970, None),
  (1971, None),
  (1972, 'Drama'),
  (1973, 'Drama'),
  (1974, 'Action'),
  (1974, 'Drama'),
  (1974, 'Thriller'),
  (1975, 'Comedy'),
  (1975, 'Music'),
  (1976, 'Drama'),
  (1976, 'Romance'),
  (1976, 'Western'),
  (1977, None),
  (1978, None),
  (1979, 'War'),
  (1980, 'Action'),
  (1980, 'Adventure'),
  (1981, 'Drama'),
  (1982, 'Drama'),
  (1983, None),
  (1984, 'Drama'),
  (1984, 'Sci-Fi'),
  (1985, None),
  (1986, 'Drama'),
  (1986, 'War'),
  (1987, None),
  (1988, 'Comedy'),
  (1988, 'Crime'),
  (1989, None),
  (1990, None),
  (1991, None),
  (1992, None),
  (1993, None),
  (1994, None),
  (1995, None),
  (1996, 'Comedy'),
  (1996, 'Drama'),
  (1996, 'Romance')]),
]
